## Pytorch basics - 60 Minute Blitz. Reference: [Pytorch.org](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)

A python-based computation package such as [Numpy](http://www.numpy.org/), and a speedy and flexible deep learning research platform.

### TENSORS

> On top of mirroring **numpy ndarrays** (n-dimensional array), **pytorch tensors** can help accelerate GPU computing (deep learning purposes). Numpy remains the  'go-to package' for ndarrays. 

In [1]:
from __future__ import print_function
import torch
import numpy as np

* An uninitialized 7 by 4 matrix (7 rows and 4 coluymns)

In [2]:
x = torch.empty(7, 4)
print(x)
type(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  4.5869e-41],
        [ 1.6276e+31,  3.0773e-41,  0.0000e+00,  0.0000e+00],
        [ 7.3908e+22,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-1.8207e+26,  4.5869e-41,  1.4013e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -2.1521e-08,  4.5869e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


torch.Tensor

* As for numpy

In [3]:
y = np.empty([7, 4])
print(y)
type(y)

[[6.01433264e+175 6.93885958e+218 5.56218858e+180 3.94356143e+180]
 [1.32412517e-071 7.16590035e-038 6.22694450e+174 6.18633154e+169]
 [5.73917536e-143 1.50008929e+248 2.59305228e-306 8.74496193e-322]
 [6.94612348e-310 4.65999776e-310 4.65999835e-310 4.65999778e-310]
 [6.94607618e-310 4.65999778e-310             nan 1.38338381e-322]
 [0.00000000e+000 6.94611455e-310 6.94607697e-310 0.00000000e+000]
 [1.52761333e+262 3.21142670e-322 4.65999835e-310 4.65999776e-310]]


numpy.ndarray

* Randomly initialized 7 by 4 matrix

In [4]:
x = torch.rand(7, 4)
print(x)
type(x)

tensor([[0.6412, 0.8474, 0.5173, 0.3816],
        [0.5540, 0.8274, 0.7321, 0.7167],
        [0.6673, 0.0033, 0.1976, 0.9670],
        [0.7375, 0.6551, 0.9248, 0.9288],
        [0.8532, 0.4927, 0.3787, 0.1674],
        [0.3049, 0.4840, 0.5114, 0.4458],
        [0.9252, 0.2005, 0.1560, 0.9287]])


torch.Tensor

* Matrix filled zeros with dtype long

In [5]:
x = torch.zeros(7, 4, dtype=torch.long)
print(x)
type(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


torch.Tensor

* numpy comparison: a 7 by 4 numpy array filled zeros

In [6]:
y = np.zeros([7, 4])
print(y)
type(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


numpy.ndarray

* A pytorch tensor straight from data

In [7]:
x = torch.tensor([7.2, 3])
print(x)
type(x)

tensor([7.2000, 3.0000])


torch.Tensor

* Numpy equivalent

In [8]:
y = np.array([7.2, 3])
print(y)
type(y)

[7.2 3. ]


numpy.ndarray

* pytorch tensor based on a existing tensor

In [9]:
x = x.new_zeros(7, 3, dtype=torch.double)
print(x)
print('')
# overriding the dimension type...
x = torch.randn_like(x, dtype=torch.float)
print(x)
print('')
# the result is a tensor of the same size.
print(x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

tensor([[ 0.1125, -0.7731, -1.3343],
        [ 0.8490, -1.4828, -0.6357],
        [-1.3173,  0.5408, -0.1278],
        [ 0.6522, -0.0345,  0.2939],
        [ 0.4726,  1.0768,  0.8550],
        [-1.8919,  0.9399, -0.6416],
        [-0.5209,  0.4455, -0.2860]])

torch.Size([7, 3])


 ==> Diving next into pytorch operations . . . 

### OPERATIONS

### (I)- Additions

In [10]:
print(x)
x.size()

tensor([[ 0.1125, -0.7731, -1.3343],
        [ 0.8490, -1.4828, -0.6357],
        [-1.3173,  0.5408, -0.1278],
        [ 0.6522, -0.0345,  0.2939],
        [ 0.4726,  1.0768,  0.8550],
        [-1.8919,  0.9399, -0.6416],
        [-0.5209,  0.4455, -0.2860]])


torch.Size([7, 3])

In [11]:
y = torch.rand(7, 3)
print(y)
y.size()

tensor([[0.2731, 0.2422, 0.5257],
        [0.9801, 0.9123, 0.9213],
        [0.4536, 0.1914, 0.3921],
        [0.6148, 0.4081, 0.5940],
        [0.1864, 0.5297, 0.2820],
        [0.2557, 0.3577, 0.1143],
        [0.3816, 0.7508, 0.0488]])


torch.Size([7, 3])

In [12]:
x_plus_y = x + y
print(f'Sum of x and y tensors: \n {x_plus_y}')
print('')
print(type(x_plus_y))
print('')
print(x_plus_y.size())

Sum of x and y tensors: 
 tensor([[ 0.3856, -0.5309, -0.8086],
        [ 1.8290, -0.5705,  0.2856],
        [-0.8637,  0.7322,  0.2643],
        [ 1.2670,  0.3736,  0.8880],
        [ 0.6589,  1.6064,  1.1370],
        [-1.6362,  1.2976, -0.5273],
        [-0.1392,  1.1963, -0.2372]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * Or equally by using **torch.add()**

In [13]:
x_plus_y = torch.add(x, y)
print(f'Sum of x and y tensors: \n {x_plus_y}')
print('')
print(type(x_plus_y))
print('')
print(x_plus_y.size())

Sum of x and y tensors: 
 tensor([[ 0.3856, -0.5309, -0.8086],
        [ 1.8290, -0.5705,  0.2856],
        [-0.8637,  0.7322,  0.2643],
        [ 1.2670,  0.3736,  0.8880],
        [ 0.6589,  1.6064,  1.1370],
        [-1.6362,  1.2976, -0.5273],
        [-0.1392,  1.1963, -0.2372]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * or by providing an output tensor as argument of the .add() function

In [14]:
# output result tensor with the same dimension as x and y
result = torch.empty(7, 4)
# addition
x_plus_y = torch.add(x, y, out=result)
print(f'Sum of x and y tensors: \n {x_plus_y}')
print('')
print(type(x_plus_y))
print('')
print(x_plus_y.size())

Sum of x and y tensors: 
 tensor([[ 0.3856, -0.5309, -0.8086],
        [ 1.8290, -0.5705,  0.2856],
        [-0.8637,  0.7322,  0.2643],
        [ 1.2670,  0.3736,  0.8880],
        [ 0.6589,  1.6064,  1.1370],
        [-1.6362,  1.2976, -0.5273],
        [-0.1392,  1.1963, -0.2372]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * In-place addition: addition mutates a the tensor y in-place, then the **add()** is suffixed with a **_**.

In [15]:
y.add_(x)
print(y)
print('')
print(type(y))
print('')
print(y.size())

tensor([[ 0.3856, -0.5309, -0.8086],
        [ 1.8290, -0.5705,  0.2856],
        [-0.8637,  0.7322,  0.2643],
        [ 1.2670,  0.3736,  0.8880],
        [ 0.6589,  1.6064,  1.1370],
        [-1.6362,  1.2976, -0.5273],
        [-0.1392,  1.1963, -0.2372]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * Traditional numpy indexing on pytorch tensors

In [18]:
# All rows of the second column from the tensor sum of x and y.
print(x_plus_y[:, 1])

tensor([-0.5309, -0.5705,  0.7322,  0.3736,  1.6064,  1.2976,  1.1963])


#### * Resizing or reshaping pytorch tensors with **torch.view()**

x = torch.randn(4, 4)
print(x)
print(x.size()) 
print('')

y = x.view(16)
print(y)
print(y.size())
print('')

z = x.view(-1, 8)   # size -1 is inferred from other dimesions.
print(x)
print(z.size())

#### * Use **.item()** to get the value as a Python number in case of one element tensor

In [37]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.type())

tensor([0.7264])
0.7263967990875244
torch.FloatTensor


In [39]:
torch.is_tensor(x)

True