## Pytorch basics - 60 Minute Blitz. Reference: [Pytorch.org](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)

A python-based computation package such as [Numpy](http://www.numpy.org/), and a speedy and flexible deep learning research platform.

### TENSORS

> On top of mirroring **numpy ndarrays** (n-dimensional array), **pytorch tensors** can help accelerate GPU computing (deep learning purposes). Numpy remains the  'go-to package' for ndarrays. 

In [1]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
print(f'Currently running pytorch version: {torch.__version__}')

Currently running pytorch version: 0.4.1


In [3]:
print(f'Supported Nvidia GPU available on the system: {torch.cuda.is_available()}')

Supported Nvidia GPU available on the system: True


In [4]:
torch.version.cuda

'8.0.61'

* An uninitialized 7 by 4 matrix (7 rows and 4 coluymns)

In [5]:
x = torch.empty(7, 4)
print(x)
type(x)

tensor([[                                      0.0000,
                                               0.0000,
                                               0.0000,
                                               0.0000],
        [                                      0.0000,
                                               0.0000,
                                               0.0000,
                                               0.0000],
        [                                      0.0000,
                                               0.0000,
                                               0.0000,
                                               0.0000],
        [                         -1803299061760.0000,
                                               0.0000,
                                               0.0000,
                                               0.0000],
        [                                      0.0000,
                                               0.0000,
      

torch.Tensor

* As for numpy

In [6]:
y = np.empty([7, 4])
print(y)
type(y)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [4.67242043e-310 4.67242041e-310 4.67242041e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 4.67242043e-310]
 [4.67242041e-310 4.67242041e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 4.67242043e-310 4.67242041e-310]
 [4.67242041e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.42290906e-321 3.16202013e-322 4.67242045e-310 4.67242041e-310]]


numpy.ndarray

* Randomly initialized 7 by 4 matrix

In [7]:
x = torch.rand(7, 4)
print(x)
type(x)

tensor([[0.2598, 0.5540, 0.1473, 0.8502],
        [0.2309, 0.7309, 0.1415, 0.7066],
        [0.5014, 0.3624, 0.2710, 0.0654],
        [0.2571, 0.2479, 0.5652, 0.9686],
        [0.6893, 0.0851, 0.0650, 0.3343],
        [0.5177, 0.0188, 0.2122, 0.4656],
        [0.2506, 0.7117, 0.8424, 0.9217]])


torch.Tensor

* Matrix filled zeros with dtype long

In [8]:
x = torch.zeros(7, 4, dtype=torch.long)
print(x)
type(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


torch.Tensor

* numpy comparison: a 7 by 4 numpy array filled zeros

In [9]:
y = np.zeros([7, 4])
print(y)
type(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


numpy.ndarray

* A pytorch tensor straight from data

In [10]:
x = torch.tensor([7.2, 3])
print(x)
type(x)

tensor([7.2000, 3.0000])


torch.Tensor

* Numpy equivalent

In [11]:
y = np.array([7.2, 3])
print(y)
type(y)

[7.2 3. ]


numpy.ndarray

* pytorch tensor based on a existing tensor

In [12]:
x = x.new_zeros(7, 3, dtype=torch.double)
print(x)
print('')
# overriding the dimension type...
x = torch.randn_like(x, dtype=torch.float)
print(x)
print('')
# the result is a tensor of the same size.
print(x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

tensor([[-1.6152,  0.6271,  2.3313],
        [-0.0707,  1.2541,  0.2749],
        [ 0.3417,  0.3235,  0.4014],
        [-0.6004, -0.0226,  1.7376],
        [ 0.0227,  0.3933, -1.1559],
        [ 0.6676, -0.1863, -0.7976],
        [-0.0128, -0.8387,  0.0233]])

torch.Size([7, 3])


 ==> Diving next into pytorch operations . . . 

### OPERATIONS

### (I)- Additions

In [13]:
print(x)
x.size()

tensor([[-1.6152,  0.6271,  2.3313],
        [-0.0707,  1.2541,  0.2749],
        [ 0.3417,  0.3235,  0.4014],
        [-0.6004, -0.0226,  1.7376],
        [ 0.0227,  0.3933, -1.1559],
        [ 0.6676, -0.1863, -0.7976],
        [-0.0128, -0.8387,  0.0233]])


torch.Size([7, 3])

In [14]:
y = torch.rand(7, 3)
print(y)
y.size()

tensor([[0.8152, 0.9466, 0.3232],
        [0.8547, 0.0691, 0.3817],
        [0.3728, 0.7139, 0.8901],
        [0.7251, 0.0020, 0.5080],
        [0.3864, 0.5815, 0.1764],
        [0.5553, 0.9525, 0.0258],
        [0.4265, 0.9817, 0.5112]])


torch.Size([7, 3])

In [15]:
x_plus_y = x + y
print(f'Sum of x and y tensors: \n {x_plus_y}')
print('')
print(type(x_plus_y))
print('')
print(x_plus_y.size())

Sum of x and y tensors: 
 tensor([[-0.8000,  1.5737,  2.6545],
        [ 0.7840,  1.3232,  0.6566],
        [ 0.7145,  1.0374,  1.2915],
        [ 0.1248, -0.0205,  2.2456],
        [ 0.4091,  0.9748, -0.9795],
        [ 1.2229,  0.7662, -0.7717],
        [ 0.4137,  0.1431,  0.5345]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * Or equally by using **torch.add()**

In [16]:
x_plus_y = torch.add(x, y)
print(f'Sum of x and y tensors: \n {x_plus_y}')
print('')
print(type(x_plus_y))
print('')
print(x_plus_y.size())

Sum of x and y tensors: 
 tensor([[-0.8000,  1.5737,  2.6545],
        [ 0.7840,  1.3232,  0.6566],
        [ 0.7145,  1.0374,  1.2915],
        [ 0.1248, -0.0205,  2.2456],
        [ 0.4091,  0.9748, -0.9795],
        [ 1.2229,  0.7662, -0.7717],
        [ 0.4137,  0.1431,  0.5345]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * or by providing an output tensor as argument of the .add() function

In [17]:
# output result tensor with the same dimension as x and y
result = torch.empty(7, 4)
# addition
x_plus_y = torch.add(x, y, out=result)
print(f'Sum of x and y tensors: \n {x_plus_y}')
print('')
print(type(x_plus_y))
print('')
print(x_plus_y.size())

Sum of x and y tensors: 
 tensor([[-0.8000,  1.5737,  2.6545],
        [ 0.7840,  1.3232,  0.6566],
        [ 0.7145,  1.0374,  1.2915],
        [ 0.1248, -0.0205,  2.2456],
        [ 0.4091,  0.9748, -0.9795],
        [ 1.2229,  0.7662, -0.7717],
        [ 0.4137,  0.1431,  0.5345]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * In-place addition: addition mutates a the tensor y in-place, then the **add()** is suffixed with a **_**.

In [18]:
y.add_(x)
print(y)
print('')
print(type(y))
print('')
print(y.size())

tensor([[-0.8000,  1.5737,  2.6545],
        [ 0.7840,  1.3232,  0.6566],
        [ 0.7145,  1.0374,  1.2915],
        [ 0.1248, -0.0205,  2.2456],
        [ 0.4091,  0.9748, -0.9795],
        [ 1.2229,  0.7662, -0.7717],
        [ 0.4137,  0.1431,  0.5345]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * Traditional numpy indexing on pytorch tensors

In [19]:
# All rows of the second column from the tensor sum of x and y.
print(x_plus_y[:, 1])

tensor([ 1.5737,  1.3232,  1.0374, -0.0205,  0.9748,  0.7662,  0.1431])


#### * Resizing or reshaping pytorch tensors with **torch.view()**

In [39]:
x = torch.randn(4, 4)
print(x)
print(x.size()) 
print('')

y = x.view(16)
print(y)
print(y.size())
print('')

z = x.view(-1, 8)   # size -1 is inferred from other dimesions.
print(z)
print(z.size())

w = x.reshape(8,2)
print(w)
print(w.shape)

tensor([[ 0.7871,  0.2454, -0.5665,  0.8359],
        [ 0.4282, -0.6261,  0.3014, -0.1588],
        [-2.5699, -0.8793,  0.2373,  0.1782],
        [-1.0572, -0.1007, -0.3016, -0.4349]])
torch.Size([4, 4])

tensor([ 0.7871,  0.2454, -0.5665,  0.8359,  0.4282, -0.6261,  0.3014, -0.1588,
        -2.5699, -0.8793,  0.2373,  0.1782, -1.0572, -0.1007, -0.3016, -0.4349])
torch.Size([16])

tensor([[ 0.7871,  0.2454, -0.5665,  0.8359,  0.4282, -0.6261,  0.3014, -0.1588],
        [-2.5699, -0.8793,  0.2373,  0.1782, -1.0572, -0.1007, -0.3016, -0.4349]])
torch.Size([2, 8])
tensor([[ 0.7871,  0.2454],
        [-0.5665,  0.8359],
        [ 0.4282, -0.6261],
        [ 0.3014, -0.1588],
        [-2.5699, -0.8793],
        [ 0.2373,  0.1782],
        [-1.0572, -0.1007],
        [-0.3016, -0.4349]])
torch.Size([8, 2])


#### * Use **.item()** to get the value as a Python number in case of one element tensor

In [20]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.type())

tensor([-0.9705])
-0.970464825630188
torch.FloatTensor


In [21]:
torch.is_tensor(x_plus_y)

True

### * Understanding Pytorch tensors: Ranks - Axes - Shapes
> Rank tells us the number of axes of the tensor :: here x_plus_y is a **Rank 2 tensor**

In [22]:
# 1rst index of axis 1 :: first element along the first axis of the tensor :: each of those eelements is an array.
print(f'1rst element of axis 1: {x_plus_y[0]}')

# 2nd index along the first axis of the tensor
print(f'2nd element of axis 1: {x_plus_y[1]}')

# 3rd index along the first axis of the tensor
print(f'3rd element of axis 1: {x_plus_y[2]}')

# 4th index along the first axis of the tensor
print(f'4th element of axis 1: {x_plus_y[3]}')

# 5th index along the first axis of the tensor
print(f'5th element of axis 1: {x_plus_y[4]}')

# 6th index along the first axis of the tensor
print(f'6th element of axis 1: {x_plus_y[5]}')

# 7th index along the first axis of the tensor
print(f'7th element of axis 1: {x_plus_y[6]}')

1rst element of axis 1: tensor([-0.8000,  1.5737,  2.6545])
2nd element of axis 1: tensor([0.7840, 1.3232, 0.6566])
3rd element of axis 1: tensor([0.7145, 1.0374, 1.2915])
4th element of axis 1: tensor([ 0.1248, -0.0205,  2.2456])
5th element of axis 1: tensor([ 0.4091,  0.9748, -0.9795])
6th element of axis 1: tensor([ 1.2229,  0.7662, -0.7717])
7th element of axis 1: tensor([0.4137, 0.1431, 0.5345])


In [23]:
# first index of axis 2 :: each of these elements is a float 
print(x_plus_y[0][0])

print(x_plus_y[1][0])

print(x_plus_y[2][0])

print(x_plus_y[4][0])

print(x_plus_y[5][0])

print(x_plus_y[6][0])

tensor(-0.8000)
tensor(0.7840)
tensor(0.7145)
tensor(0.4091)
tensor(1.2229)
tensor(0.4137)


In [24]:
# second index of axis 2 
print(x_plus_y[0][1])

print(x_plus_y[1][1])

print(x_plus_y[2][1])

print(x_plus_y[3][1])

print(x_plus_y[4][1])

print(x_plus_y[5][1])

print(x_plus_y[6][1])

tensor(1.5737)
tensor(1.3232)
tensor(1.0374)
tensor(-0.0205)
tensor(0.9748)
tensor(0.7662)
tensor(0.1431)


In [25]:
# third index of axis 2
print(x_plus_y[0][2])

print(x_plus_y[1][2])

print(x_plus_y[2][2])

print(x_plus_y[3][2])

print(x_plus_y[4][2])

print(x_plus_y[5][2])

print(x_plus_y[6][2])

tensor(2.6545)
tensor(0.6566)
tensor(1.2915)
tensor(2.2456)
tensor(-0.9795)
tensor(-0.7717)
tensor(0.5345)


#### * Kowing the shape of a tensor means knowing the length of its axes. This also tells how many indexes are available along each axis.
> The first axis has 7 indexes(length=7) and the second axis 3 indexes(length=3). In pytorch shape and size means the same thing. Don't be surprised by the result saying 'torch.Size'.

In [26]:
x_plus_y.shape

torch.Size([7, 3])

> The rank of x_plus_y is just the length of its shape.

In [30]:
rank = len(x_plus_y.shape)
print(f'x_plus_y is of rank: {rank}.')

x_plus_y is of rank: 2.


### * Tensors reshaping on Convolutional Neural Nets (CNN)
> We have here an image input as a tensor to a CNN. Also remembering that the shape of a tensor encapsulates the information on the tensor rank, axes and indexes.
