## Pytorch Basics - A 60 Minute Blitz. Reference: [Pytorch.org](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)

A python-based computation package such as [Numpy](http://www.numpy.org/), and a speedy and flexible deep learning research platform.

### TENSORS

> On top of mirroring **numpy ndarrays** (n-dimensional array), **pytorch tensors** can help accelerate GPU computing (deep learning purposes). Numpy remains the  'go-to package' for ndarrays. 

In [1]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
print(f'Currently running pytorch version: {torch.__version__}')

Currently running pytorch version: 0.4.1


In [3]:
print(f'Supported Nvidia GPU available on the system: {torch.cuda.is_available()}')

Supported Nvidia GPU available on the system: True


In [4]:
torch.version.cuda

'8.0.61'

* An uninitialized 7 by 4 matrix (7 rows and 4 coluymns)

In [5]:
x = torch.empty(7, 4)
print(x)
type(x)

tensor([[6.1146e+22, 4.5671e-41, 6.1146e+22, 4.5671e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


torch.Tensor

* As for numpy

In [6]:
y = np.empty([7, 4])
print(y)
type(y)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [4.67343581e-310 4.67343579e-310 4.67343579e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 4.67343581e-310]
 [4.67343579e-310 4.67343579e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 4.67343581e-310 4.67343578e-310]
 [4.67343578e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.42290906e-321 3.16202013e-322 4.67343583e-310 4.67343578e-310]]


numpy.ndarray

* Randomly initialized 7 by 4 matrix

In [7]:
x = torch.rand(7, 4)
print(x)
type(x)

tensor([[0.5616, 0.1875, 0.5229, 0.2906],
        [0.9674, 0.6974, 0.7566, 0.3413],
        [0.5248, 0.2511, 0.1140, 0.1679],
        [0.1047, 0.4570, 0.1143, 0.2904],
        [0.5388, 0.4611, 0.9108, 0.0192],
        [0.3632, 0.4652, 0.9261, 0.1992],
        [0.8409, 0.2861, 0.1795, 0.4132]])


torch.Tensor

* Matrix filled zeros with dtype long

In [8]:
x = torch.zeros(7, 4, dtype=torch.long)
print(x)
type(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


torch.Tensor

* numpy comparison: a 7 by 4 numpy array filled zeros

In [9]:
y = np.zeros([7, 4])
print(y)
type(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


numpy.ndarray

* A pytorch tensor straight from data

In [10]:
x = torch.tensor([7.2, 3])
print(x)
type(x)

tensor([7.2000, 3.0000])


torch.Tensor

* Numpy equivalent

In [11]:
y = np.array([7.2, 3])
print(y)
type(y)

[7.2 3. ]


numpy.ndarray

* pytorch tensor based on a existing tensor

In [12]:
x = x.new_zeros(7, 3, dtype=torch.double)
print(x)
print('')
# overriding the dimension type...
x = torch.randn_like(x, dtype=torch.float)
print(x)
print('')
# the result is a tensor of the same size.
print(x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

tensor([[ 1.5426, -0.6466, -0.6658],
        [-0.8203, -0.4404, -0.8503],
        [-0.3262,  0.3594,  0.3836],
        [ 2.0644,  0.0615, -1.1872],
        [-0.5204,  0.3759, -1.3485],
        [-0.3419,  2.1061, -1.1525],
        [ 0.5928,  0.0503,  0.9225]])

torch.Size([7, 3])


 ==> Diving next into pytorch operations . . . 

### OPERATIONS

### (I)- Additions

In [13]:
print(x)
x.size()

tensor([[ 1.5426, -0.6466, -0.6658],
        [-0.8203, -0.4404, -0.8503],
        [-0.3262,  0.3594,  0.3836],
        [ 2.0644,  0.0615, -1.1872],
        [-0.5204,  0.3759, -1.3485],
        [-0.3419,  2.1061, -1.1525],
        [ 0.5928,  0.0503,  0.9225]])


torch.Size([7, 3])

In [14]:
y = torch.rand(7, 3)
print(y)
y.size()

tensor([[0.5500, 0.7317, 0.6718],
        [0.5120, 0.7446, 0.8769],
        [0.2182, 0.5922, 0.7707],
        [0.4454, 0.9620, 0.7703],
        [0.2336, 0.3559, 0.9050],
        [0.4277, 0.8968, 0.5697],
        [0.4747, 0.9767, 0.6914]])


torch.Size([7, 3])

In [15]:
x_plus_y = x + y
print(f'Sum of x and y tensors: \n {x_plus_y}')
print('')
print(type(x_plus_y))
print('')
print(x_plus_y.size())

Sum of x and y tensors: 
 tensor([[ 2.0927,  0.0851,  0.0061],
        [-0.3082,  0.3042,  0.0266],
        [-0.1079,  0.9516,  1.1543],
        [ 2.5098,  1.0234, -0.4169],
        [-0.2868,  0.7318, -0.4436],
        [ 0.0858,  3.0029, -0.5827],
        [ 1.0675,  1.0270,  1.6139]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * Or equally by using **torch.add()**

In [16]:
x_plus_y = torch.add(x, y)
print(f'Sum of x and y tensors: \n {x_plus_y}')
print('')
print(type(x_plus_y))
print('')
print(x_plus_y.size())

Sum of x and y tensors: 
 tensor([[ 2.0927,  0.0851,  0.0061],
        [-0.3082,  0.3042,  0.0266],
        [-0.1079,  0.9516,  1.1543],
        [ 2.5098,  1.0234, -0.4169],
        [-0.2868,  0.7318, -0.4436],
        [ 0.0858,  3.0029, -0.5827],
        [ 1.0675,  1.0270,  1.6139]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * or by providing an output tensor as argument of the .add() function

In [17]:
# output result tensor with the same dimension as x and y
result = torch.empty(7, 4)
# addition
x_plus_y = torch.add(x, y, out=result)
print(f'Sum of x and y tensors: \n {x_plus_y}')
print('')
print(type(x_plus_y))
print('')
print(x_plus_y.size())

Sum of x and y tensors: 
 tensor([[ 2.0927,  0.0851,  0.0061],
        [-0.3082,  0.3042,  0.0266],
        [-0.1079,  0.9516,  1.1543],
        [ 2.5098,  1.0234, -0.4169],
        [-0.2868,  0.7318, -0.4436],
        [ 0.0858,  3.0029, -0.5827],
        [ 1.0675,  1.0270,  1.6139]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * In-place addition: addition mutates a the tensor y in-place, then the **add()** is suffixed with a **_**.

In [18]:
y.add_(x)
print(y)
print('')
print(type(y))
print('')
print(y.size())

tensor([[ 2.0927,  0.0851,  0.0061],
        [-0.3082,  0.3042,  0.0266],
        [-0.1079,  0.9516,  1.1543],
        [ 2.5098,  1.0234, -0.4169],
        [-0.2868,  0.7318, -0.4436],
        [ 0.0858,  3.0029, -0.5827],
        [ 1.0675,  1.0270,  1.6139]])

<class 'torch.Tensor'>

torch.Size([7, 3])


#### * Traditional numpy indexing on pytorch tensors

In [19]:
# All rows of the second column from the tensor sum of x and y.
print(x_plus_y[:, 1])

tensor([0.0851, 0.3042, 0.9516, 1.0234, 0.7318, 3.0029, 1.0270])


#### * Resizing or reshaping pytorch tensors with **torch.view()**

In [20]:
x = torch.randn(4, 4)
print(x)
print(x.size()) 
print('')

y = x.view(16)
print(y)
print(y.size())
print('')

z = x.view(-1, 8)   # size -1 is inferred from other dimesions.
print(z)
print(z.size())

w = x.reshape(8,2)
print(w)
print(w.shape)

tensor([[ 1.0418, -0.3099,  1.6922, -0.3365],
        [ 0.5222, -0.1985, -0.2994, -0.0609],
        [-1.5875, -0.6949,  0.1455, -1.6291],
        [-1.8647,  0.0842, -0.3113, -1.5992]])
torch.Size([4, 4])

tensor([ 1.0418, -0.3099,  1.6922, -0.3365,  0.5222, -0.1985, -0.2994, -0.0609,
        -1.5875, -0.6949,  0.1455, -1.6291, -1.8647,  0.0842, -0.3113, -1.5992])
torch.Size([16])

tensor([[ 1.0418, -0.3099,  1.6922, -0.3365,  0.5222, -0.1985, -0.2994, -0.0609],
        [-1.5875, -0.6949,  0.1455, -1.6291, -1.8647,  0.0842, -0.3113, -1.5992]])
torch.Size([2, 8])
tensor([[ 1.0418, -0.3099],
        [ 1.6922, -0.3365],
        [ 0.5222, -0.1985],
        [-0.2994, -0.0609],
        [-1.5875, -0.6949],
        [ 0.1455, -1.6291],
        [-1.8647,  0.0842],
        [-0.3113, -1.5992]])
torch.Size([8, 2])


#### * Use **.item()** to get the value as a Python number in case of one element tensor

In [21]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.type())

tensor([1.1503])
1.1503031253814697
torch.FloatTensor


In [22]:
torch.is_tensor(x_plus_y)

True

### * Understanding Pytorch tensors: Ranks - Axes - Shapes
> Rank tells us the number of axes of the tensor :: here x_plus_y is a **Rank 2 tensor**

In [23]:
# 1rst index of axis 1 :: first element along the first axis of the tensor :: each of those eelements is an array.
print(f'1rst element of axis 1: {x_plus_y[0]}')

# 2nd index along the first axis of the tensor
print(f'2nd element of axis 1: {x_plus_y[1]}')

# 3rd index along the first axis of the tensor
print(f'3rd element of axis 1: {x_plus_y[2]}')

# 4th index along the first axis of the tensor
print(f'4th element of axis 1: {x_plus_y[3]}')

# 5th index along the first axis of the tensor
print(f'5th element of axis 1: {x_plus_y[4]}')

# 6th index along the first axis of the tensor
print(f'6th element of axis 1: {x_plus_y[5]}')

# 7th index along the first axis of the tensor
print(f'7th element of axis 1: {x_plus_y[6]}')

1rst element of axis 1: tensor([2.0927, 0.0851, 0.0061])
2nd element of axis 1: tensor([-0.3082,  0.3042,  0.0266])
3rd element of axis 1: tensor([-0.1079,  0.9516,  1.1543])
4th element of axis 1: tensor([ 2.5098,  1.0234, -0.4169])
5th element of axis 1: tensor([-0.2868,  0.7318, -0.4436])
6th element of axis 1: tensor([ 0.0858,  3.0029, -0.5827])
7th element of axis 1: tensor([1.0675, 1.0270, 1.6139])


In [24]:
# first index of axis 2 :: each of these elements is a float 
print(x_plus_y[0][0])

print(x_plus_y[1][0])

print(x_plus_y[2][0])

print(x_plus_y[4][0])

print(x_plus_y[5][0])

print(x_plus_y[6][0])

tensor(2.0927)
tensor(-0.3082)
tensor(-0.1079)
tensor(-0.2868)
tensor(0.0858)
tensor(1.0675)


In [25]:
# second index of axis 2 
print(x_plus_y[0][1])

print(x_plus_y[1][1])

print(x_plus_y[2][1])

print(x_plus_y[3][1])

print(x_plus_y[4][1])

print(x_plus_y[5][1])

print(x_plus_y[6][1])

tensor(0.0851)
tensor(0.3042)
tensor(0.9516)
tensor(1.0234)
tensor(0.7318)
tensor(3.0029)
tensor(1.0270)


In [26]:
# third index of axis 2
print(x_plus_y[0][2])

print(x_plus_y[1][2])

print(x_plus_y[2][2])

print(x_plus_y[3][2])

print(x_plus_y[4][2])

print(x_plus_y[5][2])

print(x_plus_y[6][2])

tensor(0.0061)
tensor(0.0266)
tensor(1.1543)
tensor(-0.4169)
tensor(-0.4436)
tensor(-0.5827)
tensor(1.6139)


#### * Kowing the shape of a tensor means knowing the length of its axes. This also tells how many indexes are available along each axis.
> The first axis has 7 indexes(length=7) and the second axis 3 indexes(length=3). In pytorch shape and size means the same thing. Don't be surprised by the result saying 'torch.Size'.

In [27]:
x_plus_y.shape

torch.Size([7, 3])

> The rank of x_plus_y is just the length of its shape.

In [28]:
rank = len(x_plus_y.shape)
print(f'x_plus_y is of rank: {rank}.')

x_plus_y is of rank: 2.


### * Tensors reshaping on Convolutional Neural Nets (CNN)
> We have here an image input as a tensor to a CNN. Also remembering that the shape of a tensor encapsulates the information on the tensor rank, axes and indexes.
