## Pytorch basics - 60 Minute Blitz from [Pytorch.org](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)

A python-based computation package such as [Numpy](http://www.numpy.org/), and a speedy and flexible deep learning research platform.

### TENSORS

On top of being similar to numpy ndarrays (n-dimensional array), tensors in pytprch can accelerate GPU computing.

In [33]:
from __future__ import print_function
import torch
import numpy as np

* An uninitialized 7 by 4 matrix (7 rows and 4 coluymns)

In [40]:
x = torch.empty(7, 4)
print(x)
type(x)

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])


torch.Tensor

* As for numpy

In [41]:
y = np.empty([7, 4])
print(y)
type(y)

[[6.93512311e-310 6.93512311e-310 0.00000000e+000 0.00000000e+000]
 [4.66414675e-310 4.82337433e+228 6.14415221e-144 1.16097020e-028]
 [3.11550728e-033 1.48352823e-071 1.38266944e-047 3.97062373e+246]
 [1.16318408e-028 9.83696046e-072 4.79529184e+174 4.01459209e-057]
 [1.93375695e-076 5.04621361e+180 8.37170571e-144 1.32641936e+272]
 [3.59751658e+252 8.93185432e+271 4.76484771e+180 1.01849500e+248]
 [1.75520466e-033 7.11821371e-091 1.46264627e+165 1.25774452e-075]]


numpy.ndarray

* Randomly initialized 6 by 4 matrix

In [42]:
x = torch.rand(6, 4)
print(x)
type(x)

tensor([[0.0878, 0.5828, 0.1087, 0.0954],
        [0.2346, 0.7358, 0.4472, 0.2928],
        [0.1821, 0.4624, 0.4917, 0.2710],
        [0.5262, 0.3876, 0.6144, 0.8732],
        [0.4106, 0.7604, 0.8756, 0.1095],
        [0.4877, 0.3280, 0.9539, 0.4028]])


torch.Tensor

* Matrix filled zeros with dtype long

In [30]:
x = torch.zeros(6, 4, dtype=torch.long)
print(x)
type(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


torch.Tensor

* numpy comparison: a 6 by 4 numpy array filled zeros

In [29]:
y = np.zeros([6, 4])
print(y)
type(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


numpy.ndarray

* A pytorch tensor straight from data

In [46]:
x = torch.tensor([7.2, 3])
print(x)
type(x)

tensor([7.2000, 3.0000])


torch.Tensor