## Pytorch basics - 60 Minute Blitz from [Pytorch.org](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)

A python-based computation package such as [Numpy](http://www.numpy.org/), and a speedy and flexible deep learning research platform.

### TENSORS

On top of being similar to **numpy ndarrays** (n-dimensional array), **pytorch tensors** can help accelerate GPU computing.

In [33]:
from __future__ import print_function
import torch
import numpy as np

* An uninitialized 7 by 4 matrix (7 rows and 4 coluymns)

In [40]:
x = torch.empty(7, 4)
print(x)
type(x)

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])


torch.Tensor

* As for numpy

In [41]:
y = np.empty([7, 4])
print(y)
type(y)

[[6.93512311e-310 6.93512311e-310 0.00000000e+000 0.00000000e+000]
 [4.66414675e-310 4.82337433e+228 6.14415221e-144 1.16097020e-028]
 [3.11550728e-033 1.48352823e-071 1.38266944e-047 3.97062373e+246]
 [1.16318408e-028 9.83696046e-072 4.79529184e+174 4.01459209e-057]
 [1.93375695e-076 5.04621361e+180 8.37170571e-144 1.32641936e+272]
 [3.59751658e+252 8.93185432e+271 4.76484771e+180 1.01849500e+248]
 [1.75520466e-033 7.11821371e-091 1.46264627e+165 1.25774452e-075]]


numpy.ndarray

* Randomly initialized 7 by 4 matrix

In [52]:
x = torch.rand(7, 4)
print(x)
type(x)

tensor([[0.3839, 0.3017, 0.8967, 0.0507],
        [0.4906, 0.6006, 0.4217, 0.1515],
        [0.7380, 0.5615, 0.3724, 0.0727],
        [0.7210, 0.1311, 0.2222, 0.0591],
        [0.8935, 0.6887, 0.7945, 0.9134],
        [0.5425, 0.1662, 0.0146, 0.2510],
        [0.4137, 0.6768, 0.4767, 0.6763]])


torch.Tensor

* Matrix filled zeros with dtype long

In [51]:
x = torch.zeros(7, 4, dtype=torch.long)
print(x)
type(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


torch.Tensor

* numpy comparison: a 7 by 4 numpy array filled zeros

In [50]:
y = np.zeros([7, 4])
print(y)
type(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


numpy.ndarray

* A pytorch tensor straight from data

In [46]:
x = torch.tensor([7.2, 3])
print(x)
type(x)

tensor([7.2000, 3.0000])


torch.Tensor

* Numpy equivalent

In [48]:
y = np.array([7.2, 3])
print(y)
type(y)

[7.2 3. ]


numpy.ndarray

* pytorch tensor based on a existing tensor

In [62]:
x = x.new_zeros(7, 3, dtype=torch.double)
print(x)
print('')
# overriding the dimension type...
x = torch.randn_like(x, dtype=torch.float)
print(x)
print('')
# the result is a tensor of the same size.
print(x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

tensor([[ 0.8590,  0.2622, -0.0512],
        [-0.6561,  1.2328,  1.4371],
        [ 1.1176, -0.1060,  0.0074],
        [ 1.3129, -0.6759, -0.7998],
        [-0.8473,  1.5382, -0.2880],
        [ 1.7734, -0.2852,  1.1908],
        [ 0.8955, -0.7059, -1.1326]])

torch.Size([7, 3])


 ==> Diving into pytorch operations on the next page . . .